FROM php:8.1-apache

ARG USER_ID
ARG GROUP_ID

# Install and enable apache modules
RUN echo "ServerName localhost" >> /etc/apache2/apache2.conf \
    \
    &&  apt-get update \
    &&  apt-get install -y --no-install-recommends \
    locales apt-utils git libicu-dev g++ libpng-dev libxml2-dev libzip-dev libonig-dev libxslt-dev unzip nodejs npm wget

#### Apache config
RUN a2enmod rewrite

# Ensure Apache PID file is removed on start
RUN rm -f /var/run/apache2/apache2.pid

# Install language
RUN echo "en_US.UTF-8 UTF-8" > /etc/locale.gen  \
    &&  echo "fr_FR.UTF-8 UTF-8" >> /etc/locale.gen \
    &&  locale-gen

# composer
RUN curl -sS https://getcomposer.org/installer | php -- \
    &&  mv composer.phar /usr/local/bin/composer

# Symfony CLI
RUN curl -sS https://get.symfony.com/cli/installer | bash \
    && mv /root/.symfony5/bin/symfony /usr/local/bin

# Docker modules
RUN docker-php-ext-configure \
    intl \
    &&  docker-php-ext-install \
    pdo pdo_mysql opcache intl zip calendar dom mbstring gd xsl \
    \
    &&  pecl install apcu && docker-php-ext-enable apcu

# Change user inside container to avoid permission issues
RUN usermod -u ${USER_ID} www-data
RUN groupmod -g ${GROUP_ID} www-data 
RUN chown -R www-data:www-data /var/www

# Define the user to run the container
USER www-data

EXPOSE 80

# Start apache
CMD ["apache2-foreground"]

# Set working directory
WORKDIR /var/www/html/
